### ISSUE TITLE
How do i compress it again?

### ISSUE THREAD

**Issue by GuckTubeYT** [krisudom/reversing-tenda-n301#1]
how do i compress it again and is it need to sign the firmware?
because i want to make custom firmware

**Comment by bread-b4nk** [comment]
I think you can just recompress it using [lzma](https://docs.python.org/3/library/lzma.html#compressing-and-decompressing-data-in-memory) since we decompressed it with no special configurations. We never got far enough as to put in modified firmware, so we're not sure if it needs to be signed or not. That being said, we didn't find any signatures though. Try putting in an unsigned compressed version and please let us know how it went!

**Comment by GuckTubeYT** [comment]
Btw, can you help me about get hash crc32?

**Comment by GuckTubeYT** [comment]
when i try to upload my tenda F3 custom firmware, its failed
when i try check the CRC32 hash, its like this

Original CRC32 Hash = 0x84EA2E8F
When i re hash the original file = 0xCC1EA692

Please help me

**Comment by bread-b4nk** [comment]
We can generate a CRC32 hash collision, CRC is not a cryptographic hash so there's a way to generate a hash collision trivially. I found this online: https://www.nayuki.io/page/forcing-a-files-crc-to-any-value . I haven't tested it, but give that a try, hopefully you can make your file have the same CRC32 hash. Let me know how it goes!

**Comment by GuckTubeYT** [comment]
Oh okay, btw if you want to try it, this is a link = https://www.tenda.com.cn/download/detail-2440.html

**Comment by GuckTubeYT** [comment]
So, i want to translate chinese language to english language, thats why i want to make custom firmware

**Comment by GuckTubeYT** [comment]
And btw, thanks for the information, i try it later
